version: "3.7"

services:
  hse-remind:
    build:
      context: .
      dockerfile: ./hse-remind/deploy/Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE
      - BOT_TOKEN
      - YOUTUBE_KEY

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  postgres-kks:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: kks
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-data-kks:/data/postgres
    ports:
      - 5432:5432

  postgres-lifestats:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: lifestats
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-data-lifestats:/data/postgres
    ports:
      - 5432:5432

volumes:
  mongo-data:
  postgres-data-kks:
  postgres-data-lifestats:

