version: "3.7"

services:
  hse-remind:
    build:
      context: .
      dockerfile: ./hse-remind/deploy/Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BOT_TOKEN

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
