version: "3.7"

services:
  hse-remind:
    build:
      context: .
      dockerfile: ./hse-remind/deploy/Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE
      - BOT_TOKEN
      - YOUTUBE_KEY

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  kks-stat:
    build:
      context: .
      dockerfile: ./kks-stat/deploy/Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE
      - VIRTUAL_HOST=kks.darkkeks.me

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: kks
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

volumes:
  mongo-data:
  postgres-data:
