---
# Default profile is dev
spring.profiles.active: dev

telegram:
  token: ${BOT_TOKEN}

ruz:
  base_url: 'https://ruz.hse.ru/api/'
---
# Override some properties in dev profile
spring.profiles: dev
