---
# Default profile is dev
spring.profiles.active: dev

spring.data.mongodb.host: mongo

telegram:
  token: ${BOT_TOKEN}

ruz:
  base_url: 'https://ruz.hse.ru/api/'


---
spring.profiles: staging


---
spring.profiles: dev

spring.data.mongodb.host: localhost
