---
chats:
- name: "195 Общий"
  target:
    channel: -1001579713051
  lecture_rules:
  - source:
      group: "БПМИ195"
- name: "196 Общий"
  target:
    channel: -1001771166134
  lecture_rules:
  - source:
      group: "БПМИ196"
version: 1

