---
chats:
  - # Название группы правил, пока не используется
    name: "193 Общий"

    # Куда отсылать уведомления, одно из
    #   channel: 123123
    #   group: 123123
    #   me: true
    target:
      channel: -1001477647138

    # Список правил. Правило -- это комбинация "откуда брать лекции" и "чем их фильтровать"
    lecture_rules:
      - # source -- откуда из расписания брать лекции
        # Здесь, берутся лекции группы БПМИ193
        # Кроме group, можно указать student: "Балюк"
        source:
          group: "БПМИ193"

        # Все лекции перед уведомлением проходят через фильтр
        # Фильтры очень гибкие, но возможно чуть сложны для понимания
        # В примере ниже приходит уведомление о всех лекциях, кроме лекций по средам
        filter:
          none_of:
            - week_days:
                - 3

  - name: "Личка"
    target:
      me: true
    lecture_rules:
      - source:
          group: "БПМИ193"

        # Все лекции группы 193, кроме
        # - лекций по средам
        # - не моих семов по алгосам
        # - семов по матану
        # - семов по твимс
        filter:
          none_of:
            - week_days:
                - 3
            - all_of:
                - lecture_type: "Семинар"
                - lecture_name: ".*Математический анализ.*"
            - all_of:
                - lecture_type: "Семинар"
                - lecture_name: ".*Теория вероятностей.*"
      - source:
          group: "БПМИ195"

        # Семы по матану и твимс группы 195
        filter:
          all_of:
            - lecture_type: "Семинар"
            - any_of:
                - lecture_name: ".*Математический анализ.*"
                - lecture_name: ".*Теория вероятностей.*"

      - source:
          lecturer: "Новиков Борис Асенович"
        filter:
          lecture_name: '.*Технологии баз данных.*'


  - name: "Лекции"
    target:
      channel: -1001240134828

    # Брать видео из плейлистов ютаба
    youtube_rules:
      - source:
          # хештег под видео
          name: 'ДМ2'
          # id плейлиста (можно скопировать из ссылки на плейлист)
          playlist: 'PLEwK9wdS5g0rlJ8sZo5x0rJYRdl4XFeZt'
      - source:
          name: 'ДМ2'
          playlist: 'PL1Uob8iPTHGRZB9F2yjqXhGp75g1ZJFk-'
      - source:
          name: 'ТВиМС'
          playlist: 'PLEwK9wdS5g0rSOfuEG8wmghP682aEPPud'
      - source:
          name: 'МА2'
          playlist: 'PLEwK9wdS5g0qV-430pfXzTawd6pI_VUgq'
version: 1
